### ISSUE TITLE
Search users by skills

### ISSUE THREAD

**Issue by hizxle** [gurovic/linkedin#51]
As a user, I want to search for other users based on their skills, so that I can find potential collaborators or employees with specific expertise for projects or job openings.

### Tasks:
- [ ] Create a search interface that allows filtering users by skills
- [ ] Display search results showing users who have the searched skill
- [ ] Include basic user information in the search results
