### ISSUE TITLE
Interactive Alumni Distribution Map

### ISSUE THREAD

**Issue by IceDarold** [gurovic/linkedin#73]
Develop an interactive map that displays the global distribution of alumni. Users will see large clusters representing alumni concentrations, which break down into smaller clusters as they zoom in, until each individual alumni is represented by a single point. Clicking on a point will show the profile of that alumni. Different colors will represent alumni profiles.

- [x] Find an open source map for the implementation into our site
- [x] Set up the map's API
- [x] Download an IDE
- [x] #75 
- [x] #76 
- [x] #77 
- [x] #78 
- [x] #80
- [x] #81 
- [x] #82 
- [x] #83 
- [x] #85 
- [x] #86 
- [x] #95
