### ISSUE TITLE
Setting up the base map (Leaflet/Mapbox)

### ISSUE THREAD

**Issue by IceDarold** [gurovic/linkedin#75]
## User Story:
As a developer, I need to install and configure a mapping library (Leaflet/Mapbox) so that the interactive map can display geographical data, allowing users to see the distribution of alumni across the world.

## Tasks:
- [x] Install and integrate Leaflet/Mapbox into the project.
- [x] Set up a map with a basic tile layer (e.g., OpenStreetMap).
- [x] Define initial coordinates and zoom level.
