### ISSUE TITLE
Implement marker clustering

### ISSUE THREAD

**Issue by IceDarold** [gurovic/linkedin#77]
## User Story
As a developer, I need to implement marker clustering so that when users view the map at a larger scale, alumni markers are grouped into clusters to improve visibility and performance.

## Tasks

- [ ] Install and configure Leaflet.markercluster or a similar solution.
- [ ] Set up the clustering logic and display the number of alumni in each cluster.
- [ ] Implement zoom-based cluster breakdown.
