### ISSUE TITLE
Adjusting cluster size and colors

### ISSUE THREAD

**Issue by IceDarold** [gurovic/linkedin#78]
## User Story
As a developer, I need to adjust the size and color of clusters based on the number of alumni and their profile types so that users can visually differentiate between groups of alumni.

## Tasks
- [ ] Add functionality for dynamic resizing of clusters.
- [ ] Set different cluster colors based on alumni profile types.
- [ ] Test on different zoom levels.
